# Generated by Django 5.1.2 on 2024-10-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_matching', '0004_alter_group_admin_user_alter_chat_user_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=10),
            preserve_default=False,
        ),
    ]
